### ISSUE TITLE
Update pdf with latest version

### ISSUE THREAD

**Issue by SijmenHuizenga** [code-star/freelancer-leaderboard#3]
Hi! Thanks a lot for creating this amazing challenge!! It has entertained me for many nights already. :heart: 

The pdf on the website was updated with some new rules. For completeness-sake, would it be possible to also add the pdf here? If you want me to file a PR I would be happy to do so.

**Comment by mdvanes** [comment]
Thanks for your kind words, good to hear it has been entertaining! I'll forward it to the creator of the challenge and we'll add the PDF.

**Comment by mdvanes** [comment]
Updated docs and PDF
